version: '3'
services:
  web:
    build:
      context: .
    image: kanka
    container_name: kanka
    ports:
      - ${DOCKER_WEB_PORT}:80
    env_file:
      - .docker/web/variables.env
    environment:
      APP_DEBUG: ${APP_DEBUG}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}
      DB_HOST: database
      # DB_CONNECTION: mysql
      # DB_DATABASE: kanka_test
      # DB_USERNAME: homestead
      # DB_PASSWORD: secret
      REDIS_HOST: redis
    depends_on:
      - database
      - redis

  database:
    image: mariadb:10
    restart: unless-stopped
    environment:
     MYSQL_USER: ${DB_USERNAME}
     MYSQL_PASSWORD: ${DB_PASSWORD}
     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
     MYSQL_DATABASE: ${DB_DATABASE}
    ports:
     - ${DOCKER_DB_PORT}:3306

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    # volumes:
    #   - /data/redis:/data
 